[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "simd_personality"
description = "Support for multiple kernel personalities: SIMD and non-SIMD"
version = "0.1.0"

[dependencies]
cfg-if = "0.1.6"

[dependencies.pit_clock]
path = "../pit_clock"

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../memory"

[dependencies.task]
path = "../task"

[dependencies.spawn]
path = "../spawn"

[dependencies.apic]
path = "../apic"

[dependencies.mod_mgmt]
path = "../mod_mgmt"

[dependencies.fs_node]
path = "../fs_node"

# [target.'cfg(target_feature = "sse2")'.dependencies.compiler_builtins]
# git = "https://github.com/rust-lang-nursery/compiler-builtins"
# features = [ "no-lang-items" ]

[lib]
crate-type = ["rlib"]
