[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "rendezvous"
description = "Synchronous Inter-Task Communication using a rendezvous approach"
version = "0.1.0"

[dependencies]
spin = "0.9.0"

[dependencies.log]
version = "0.4.8"

[dependencies.debugit]
path = "../../libs/debugit"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.task]
path = "../task"

[dependencies.scheduler]
path = "../scheduler"

[dependencies.wait_queue]
path = "../wait_queue"

[dependencies.hpet]
path = "../acpi/hpet"


[lib]
crate-type = ["rlib"]
