[package]
name = "test_mutex_sleep"
version = "0.1.0"
description = "Tests the blocking sleeping mutex with multiple tasks"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies.log]
version = "0.4.8"

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.task]
path = "../../kernel/task"

[dependencies.cpu]
path = "../../kernel/cpu"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.mutex_sleep]
path = "../../kernel/mutex_sleep"
