[package]
authors = ["Namitha Liyanage <Namithaliyanage@gmail.com>"]
name = "runqueue_priority"
description = "Functions and types for handling runqueues when priority scheduler is in use, i.e., lists of tasks for scheduling purposes"
version = "0.1.0"

[dependencies]
log = "0.4.8"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[dependencies.task]
path = "../task"

## This should be dependent upon 'cfg(single_simd_task_optimization)',
## but it cannot be because of https://github.com/rust-lang/cargo/issues/5499.
## Therefore, it has to be unconditionally included.
[dependencies.single_simd_task_optimization]
path = "../single_simd_task_optimization"


[lib]
crate-type = ["rlib"]
