[package]
authors = ["Ramla Ijaz <ijazramla@gmail.com>"]
name = "multiple_heaps"
description = "Allocator which uses multiple heaps"
version = "0.1.0"

[dependencies]
intrusive-collections = "0.9.0"
cfg-if = "0.1.6"
spin = "0.9.4"


[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../memory"

[dependencies.page_allocator]
path = "../page_allocator"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.apic]
path = "../apic"

[dependencies.slabmalloc]
path = "../slabmalloc"

[dependencies.slabmalloc_safe]
path = "../slabmalloc_safe"

[dependencies.slabmalloc_unsafe]
path = "../slabmalloc_unsafe"

[dependencies.heap]
path = "../heap"

[dependencies.hashbrown]
version = "0.11.2"
features = ["nightly"]
