[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "runqueue"
description = "Functions and types for handling runqueues, i.e., lists of tasks for scheduling purposes"
version = "0.1.0"

[dependencies]

[dependencies.cfg-if]
version = "1.0.0"

[dependencies.log]
version = "0.4.8"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.4.0"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[dependencies.task]
path = "../task"

[dependencies.runqueue_round_robin]
path = "../runqueue_round_robin"

[dependencies.runqueue_priority]
path = "../runqueue_priority"

[dependencies.runqueue_realtime]
path = "../runqueue_realtime"

## This should be dependent upon 'cfg(single_simd_task_optimization)',
## but it cannot be because of https://github.com/rust-lang/cargo/issues/5499.
## Therefore, it has to be unconditionally included.
[dependencies.single_simd_task_optimization]
path = "../single_simd_task_optimization"


[lib]
crate-type = ["rlib"]
