[package]
name = "rsdp"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI RSDP"

[dependencies]
owning_ref = { git = "https://github.com/theseus-os/owning-ref-rs" }
zerocopy = "0.5.0"

[dependencies.memory]
path = "../../memory"
