[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "frame_allocator"
description = "The allocator for physical memory frames."
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.8"
spin = "0.9.4"
static_assertions = "1.1.0"
intrusive-collections = "0.9.0"

range_inclusive = { path = "../../libs/range_inclusive" }

kernel_config = { path = "../kernel_config" }
memory_structs = { path = "../memory_structs" }

