[package]
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>"]
description = "Allows configuring the Generic Interrupt Controller"
version = "0.1.0"
edition = "2021"
name = "gic"

[dependencies]
zerocopy = "0.5.0"
volatile = "0.2.7"
spin = "0.9.4"
log = "0.4.8"

memory = { path = "../memory" }
cpu = { path = "../cpu" }
arm_boards = { path = "../arm_boards" }
