[package]
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>"]
description = "Allows configuring the Generic Interrupt Controller"
version = "0.1.0"
edition = "2021"
name = "gic"

[dependencies]
static_assertions = "1.1.0"
arrayvec = { version = "0.7.2", default-features = false }
bitflags = "1.1.0"
zerocopy = "0.5.0"
log = "0.4.8"

memory = { path = "../memory" }
cpu = { path = "../cpu" }
arm_boards = { path = "../arm_boards" }
