[package]
name = "vfs_node"
version = "0.1.0"
authors = ["Andrew Pham <apham727@gmail.com>, Christine Wang <chrissywang54@gmail.com"]
description = "contains the structs VFSDirectory and VFSFile, which are the most basic, generic implementers of the traits Directory and File, respectively. "


[dependencies]
spin = "0.9.0"

[dependencies.log]
version = "0.4.8"

[dependencies.fs_node]
path = "../fs_node"

[dependencies.memory]
path = "../memory"

[lib]
crate-type = ["rlib"]
