[package]
name = "window_manager"
version = "0.1.0"
authors = ["Yue Wu <wuyue16@pku.edu.cn>", "Wenqiu Yu <yuwenqiuj@gmail.com>"]
description = "allocate new windows and manage a list of existing windows"

[dependencies]
spin = "0.9.0"
mpmc = "0.1.6"

[dependencies.log]
version = "0.4.8"

[dependencies.framebuffer_drawer]
path = "../framebuffer_drawer"

[dependencies.window_inner]
path = "../window_inner"

[dependencies.compositor]
path = "../compositor"

[dependencies.framebuffer_compositor]
path = "../framebuffer_compositor"

[dependencies.shapes]
path = "../shapes"

[dependencies.framebuffer]
path = "../framebuffer"

[dependencies.color]
path = "../color"

[dependencies.event_types]
path = "../event_types"

[dependencies.font]
path = "../font"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.4.0"

[dependencies.mod_mgmt]
path = "../mod_mgmt"

[dependencies.spawn]
path = "../spawn"

[dependencies.mouse_data]
path = "../../libs/mouse_data"

[dependencies.path]
path = "../../kernel/path"

[lib]
crate-type = ["rlib"]

[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"

[dependencies.scheduler]
path = "../../kernel/scheduler"
