[package]
name = "heapfile"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "An implementation of in-memory files, backed by heap memory"


[dependencies]
spin = "0.9.0"

[dependencies.fs_node]
path = "../fs_node"

[dependencies.memory]
path = "../memory"

[dependencies.log]
version = "0.4.8"

[dependencies.io]
path = "../io"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[lib]
crate-type = ["rlib"]
