[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "exceptions_early"
description = "Early exception handlers that do nothing but print an error and hang."
version = "0.1.0"
build = "../../build.rs"

[dependencies]
x86_64 = { path = "../../libs/x86_64" } # currently using our local copy, forked from Phil Opp's crate
spin = "0.7.1"

[dependencies.memory]
path = "../memory"

[dependencies.vga_buffer]
path = "../vga_buffer"

[dependencies.mod_mgmt]
path = "../mod_mgmt"

[dependencies.tss]
path = "../tss"

[dependencies.gdt]
path = "../gdt"


[lib]
crate-type = ["rlib"]
