[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "exceptions_early"
description = "Early exception handlers that do nothing but print an error and hang."
version = "0.1.0"
edition = "2018"

[dependencies]
x86_64 = "0.14.8"
spin = "0.9.4"
locked_idt = { path = "../../libs/locked_idt" }

[dependencies.memory]
path = "../memory"

[dependencies.early_printer]
path = "../early_printer"

[dependencies.mod_mgmt]
path = "../mod_mgmt"

[dependencies.tss]
path = "../tss"

[dependencies.gdt]
path = "../gdt"

[dependencies.pause]
path = "../pause"


[lib]
crate-type = ["rlib"]
