[package]
name = "test_downtime"
version = "0.1.0"
description = "Measure the downtime when various subsystems crash"
authors = ["Namitha Liyanage <namithaliyanage@gmail.com>"]

[dependencies]
getopts = "0.2.21"
spin = "0.9.4"

[dependencies.app_io]
path = "../../kernel/app_io"

[dependencies.log]
version = "0.4.8"

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.task]
path = "../../kernel/task"

[dependencies.cpu]
path = "../../kernel/cpu"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.rendezvous]
path = "../../kernel/rendezvous"

[dependencies.async_channel]
path = "../../kernel/async_channel"

# for WM

[dependencies.window]
path = "../../kernel/window"

[dependencies.shapes]
path = "../../kernel/shapes"

[dependencies.color]
path = "../../kernel/color"

[dependencies.framebuffer]
path = "../../kernel/framebuffer"

[dependencies.framebuffer_drawer]
path = "../../kernel/framebuffer_drawer"

[dependencies.runqueue]
path = "../../kernel/runqueue"

[dependencies.hpet]
path = "../../kernel/acpi/hpet"

[dependencies.unified_channel]
path = "../../kernel/unified_channel" 
