[package]
name = "crate_metadata"
version = "0.1.0"
description = "Types for tracking loaded crates and their dependency metadata within Theseus's CrateNamespaces"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
build = "../../build.rs"


[dependencies]
spin = "0.4.10"
xmas-elf = { version = "0.6.2", git = "https://github.com/kevinaboos/xmas-elf.git" }


[dependencies.log]
default-features = false
version = "0.3.7"

### used for linker relocation typedefs
[dependencies.goblin]
version = "0.0.19"
default-features = false
features = ["elf64"]

[dependencies.cow_arc]
path = "../../libs/cow_arc"

[dependencies.hashbrown]
version = "0.1.8"
features = ["nightly"]

[dependencies.memory]
path = "../memory"

[dependencies.fs_node]
path = "../fs_node"

[lib]
crate-type = ["rlib"]
