[package]
authors = ["Ramla Ijaz <ijazramla@gmail.com>"]
name = "memory_initialization"
description = "Initialization routine for the virtual memory subsystem."
version = "0.1.0"

[dependencies]
multiboot2 = "0.14.0"

[dependencies.memory]
path = "../memory"

[dependencies.stack]
path = "../stack"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.bootloader_modules]
path = "../bootloader_modules"

[dependencies.log]
version = "0.4.8"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.heap]
path = "../heap"
