[package]
name = "font"
version = "0.1.0"
authors = ["Wenqiu Yu <yuwenqiuj@gmail.com>"]
description = "define and initialize the bitmaps of ASCII characters"
build = "../../build.rs"

[dependencies]
spin = "0.4.10"

[lib]
crate-type = ["rlib"]
