[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "ata"
description = "Storage device driver for ATA (IDE) disks"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1.1.0"
log = "0.4.8"
spin = "0.9.0"
x86_64 = "0.14.8"

[dependencies.port_io]
path = "../../libs/port_io"

[dependencies.interrupts]
path = "../interrupts"

[dependencies.pci]
path = "../pci"

[dependencies.storage_device]
path = "../storage_device"

[dependencies.io]
path = "../io"


[lib]
crate-type = ["rlib"]
