[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "ata"
description = "Support for accessing ATA (IDE) disks"
version = "0.1.0"

[dependencies]
bitflags = "1.1.0"
spin = "0.9.0"

[dependencies.log]
version = "0.4.8"

[dependencies.port_io]
path = "../../libs/port_io"

[dependencies.pci]
path = "../pci"

[dependencies.storage_device]
path = "../storage_device"

[dependencies.io]
path = "../io"


[lib]
crate-type = ["rlib"]
