[package]
name = "keyboard_echo"
version = "0.1.0"
authors = ["Zhiyao Ma <zm16@pku.edu.cn>"]

[dependencies]
core2 = { version = "0.4.0", default-features = false, features = ["alloc", "nightly"] }

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.app_io]
path = "../../kernel/app_io"

[dependencies.log]
version = "0.4.8"

[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"

[lib]
crate-type = ["rlib"]
