[package]
name = "fault_log"
version = "0.1.0"
description = "Logs all exceptions occuring in Theseus"
authors = ["Namitha Liyanage <namithaliyanage@gmail.com>"]


[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.memory]
path = "../memory"

[dependencies.vga_buffer]
path = "../vga_buffer"

[dependencies.app_io]
path = "../app_io"

[dependencies.task]
path = "../task"

[dependencies.cpu]
path = "../cpu"

[dependencies.log]
default-features = false
version = "0.4.8"

