[package]
name = "iommu"
version = "0.1.0"
authors = ["Nicholas Lindsay <nlindsay747@gmail.com>"]
description = "Intel VT-d IOMMU support"

[dependencies]
log = "0.4.8"
spin = "0.9.4"
volatile = "0.2.7"
zerocopy = "0.5.0"
bitflags = "1.3.2"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.memory]
path = "../memory"

[lib]
crate-type = ["rlib"]
