[package]
authors = ["Namitha Liyanage <namithaliyanage@gmail.com>"]
name = "scheduler_priority"
description = "Provides priority scheduling functionality and picks the next task"
version = "0.1.0"

[dependencies]
spin = "0.9.0"

[dependencies.log]
version = "0.4.8"

[dependencies.task]
path = "../task"

[dependencies.runqueue]
path = "../runqueue"

[dependencies.runqueue_priority]
path = "../runqueue_priority"

[lib]
crate-type = ["rlib"]
