[package]
name = "hpet"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for the x86 HPET: High Precision Event Timer"
build = "../../build.rs"
edition = "2018"

[dependencies]
spin = "0.4.10"
volatile = "0.2.7"
owning_ref = { git = "https://github.com/kevinaboos/owning-ref-rs" }
zerocopy = "0.3.0"

[dependencies.log]
version = "0.4.8"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.memory]
path = "../memory"

[dependencies.sdt]
path = "../sdt"

[dependencies.acpi_table]
path = "../acpi_table"
