[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "page_table_entry"
description = "Defines the structure of page table entries on x86_64"
version = "0.1.0"
edition = "2018"

[dependencies]
bit_field = "0.7.0"
zerocopy = "0.5.0"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.memory_structs]
path = "../memory_structs"

[dependencies.frame_allocator]
path = "../frame_allocator"

[lib]
crate-type = ["rlib"]
