[package]
name = "test_sync_block"
version = "0.1.0"
description = "Tests the blocking sleeping mutex with multiple tasks"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
edition = "2021"

[dependencies.log]
version = "0.4.8"

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.task]
path = "../../kernel/task"

[dependencies.cpu]
path = "../../kernel/cpu"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.sync_block]
path = "../../kernel/sync_block"
