[package]
name = "ls"
version = "0.1.0"
authors = ["Christine Wang <chrissywang54@gmail.com>"]

[dependencies]
getopts = "0.2.21"

[dependencies.log]
version = "0.4.8"


[dependencies.app_io]
path = "../../kernel/app_io"

[dependencies.task]
path = "../../kernel/task"

[dependencies.fs_node]
path = "../../kernel/fs_node"

[dependencies.path]
path = "../../kernel/path"

# [dependencies.application_main_fn]
# path = "../../compiler_plugins"