[package]
authors = ["Ramla Ijaz <ijazramla@gmail.com>"]
name = "virtual_nic"
description = "A structure that allows a physical NIC to partition its resources"
version = "0.1.0"
build = "../../build.rs"

[dependencies]

[dependencies.nic_buffers]
path = "../nic_buffers"

[dependencies.nic_queues]
path = "../nic_queues"

[dependencies.network_interface_card]
path = "../network_interface_card"

[dependencies.physical_nic]
path = "../physical_nic"

[dependencies.intel_ethernet]
path = "../intel_ethernet"

[dependencies.irq_safety]
git = "https://github.com/kevinaboos/irq_safety"

[dependencies.wakelock]
path = "../wakelock"

[lib]
crate-type = ["rlib"]
