[package]
name = "rm"
version = "0.1.0"
authors = ["Andrew Pham <apham@rice.edu"]
description = "removes the directory from the virtual filesystem"

[dependencies]
getopts = "0.2.21"

[dependencies.terminal_print]
path = "../../kernel/terminal_print"

[dependencies.task]
path = "../../kernel/task"

[dependencies.path]
path = "../../kernel/path"

[dependencies.fs_node]
path = "../../kernel/fs_node"

[dependencies.root]
path = "../../kernel/root"

[dependencies.log]
version = "0.4.8"


# [dependencies.application_main_fn]
# path = "../../compiler_plugins"
