[package]
name = "text_display"
version = "0.1.0"
authors = ["Wenqiu Yu <yuwenqiuj@gmail.com>"]
description = "a text display is a block of text which can display onto a framebuffer"
build = "../../../build.rs"

[dependencies]
spin = "0.9.0"

[dependencies.framebuffer]
path = "../../../kernel/framebuffer"

[dependencies.displayable]
path = "../"

[dependencies.framebuffer_printer]
path = "../../framebuffer_printer"

[dependencies.font]
path = "../../../kernel/font"

[dependencies.shapes]
path = "../../../kernel/shapes"

[dependencies.color]
path = "../../../kernel/color"

[lib]
crate-type = ["rlib"]
