[package]
name = "print"
version = "0.1.0"
authors = ["Andrew Pham <apham727@gmail.com>"]
description = "offers kernel crates the ability to print to the default terminal"

[dependencies]
spin = "0.9.0"


[dependencies.dfqueue]
path = "../../libs/dfqueue"

[dependencies.event_types]
path = "../event_types"


[dependencies.log]
version = "0.4.8"
