[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "scheduler_round_robin"
description = "Provides Round robin scheduling functionality and picks the next task"
version = "0.1.0"

[dependencies]
spin = "0.9.0"

[dependencies.log]
version = "0.4.8"

[dependencies.task]
path = "../task"

[dependencies.runqueue]
path = "../runqueue"

[dependencies.runqueue_round_robin]
path = "../runqueue_round_robin"

[lib]
crate-type = ["rlib"]
