[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "wait_condition"
description = "Wait condition variables that can block/sleep and wake up tasks"
version = "0.1.0"


# [dependencies.log]
# default-features = false
# version = "0.4.8"

[dependencies.task]
path = "../task"

[dependencies.wait_queue]
path = "../wait_queue"

[lib]
crate-type = ["rlib"]
