[package]
name = "hello"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]


[dependencies.log]
version = "0.4.8"


[dependencies.print]
path = "../../kernel/print"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
