[package]
name = "test_channel"
version = "0.1.0"
description = "Tests Theseus's channel implementations with multiple tasks"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]
getopts = "0.2.21"
spin = "0.9.4"

[dependencies.app_io]
path = "../../kernel/app_io"

[dependencies.log]
version = "0.4.8"

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.task]
path = "../../kernel/task"

[dependencies.cpu]
path = "../../kernel/cpu"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.rendezvous]
path = "../../kernel/rendezvous"

[dependencies.async_channel]
path = "../../kernel/async_channel"
