[package]
name = "test_channel"
version = "0.1.0"
description = "Tests Theseus's channel implementations with multiple tasks"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]
getopts = "0.2.21"
spin = "0.9.0"

[dependencies.terminal_print]
path = "../../kernel/terminal_print"

[dependencies.log]
version = "0.4.8"

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.task]
path = "../../kernel/task"

[dependencies.apic]
path = "../../kernel/apic"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.rendezvous]
path = "../../kernel/rendezvous"

[dependencies.async_channel]
path = "../../kernel/async_channel"
