[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "tss"
description = "TSS (Task State Segment support (x86 only) for Theseus"
version = "0.1.0"

[dependencies]
log = "0.4.8"
spin = "0.9.0"
x86_64 = "0.14.8"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[dependencies.memory]
path = "../memory"

[dependencies.apic]
path = "../apic"


[lib]
crate-type = ["rlib"]
