[package]
authors = ["Ramla Ijaz <ijazramla@gmail.com>"]
name = "heap"
description = "global allocator for the system"
version = "0.1.0"

[dependencies]
spin = "0.9.4"

[dependencies.log]
version = "0.4.8"

[dependencies.sync_irq]
path = "../../libs/sync_irq"

[dependencies.memory]
path = "../memory"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.block_allocator]
path = "../block_allocator"
