[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "exceptions_full"
description = "Exception handlers that are fully-featured, i.e., aware of the apic/task subsystems, and kill tasks on an exception"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
# x86_64 = { git = "https://github.com/kevinaboos/x86_64" }
x86_64 = { path = "../../libs/x86_64" } # currently using our local copy, forked from Phil Opp's crate

[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.gimli]
version = "0.19.0"
default-features = false
features = [ "read", "alloc" ]

[dependencies.vga_buffer]
path = "../vga_buffer"

[dependencies.print]
path = "../print"

[dependencies.apic]
path = "../apic"

[dependencies.tlb_shootdown]
path = "../tlb_shootdown"

[dependencies.task]
path = "../task"

[dependencies.runqueue]
path = "../runqueue"

[dependencies.fault_log]
path = "../fault_log"

[dependencies.pmu_x86]
path = "../pmu_x86"

[dependencies.unwind]
path = "../unwind"

[dependencies.memory]
path = "../memory"

[dependencies.stack_trace]
path = "../stack_trace"

[dependencies.debug_info]
path = "../debug_info"

[lib]
crate-type = ["rlib"]
