[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "ethernet_smoltcp_device"
description = "An interface glue layer that allows smoltcp to use ethernet crates"
version = "0.1.0"

[dependencies]
owning_ref = { git = "https://github.com/theseus-os/owning-ref-rs" }


[dependencies.log]
version = "0.4.8"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.4.0"


[dependencies.smoltcp]
version = "0.5.0"
default-features = false
features = [
    "alloc", "ethernet",
    # "log", "verbose", 
    "proto-ipv4", "proto-igmp", "proto-ipv6", "proto-dhcpv4",
    "socket-raw", "socket-udp", "socket-tcp", "socket-icmp", 
]

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.memory]
path = "../memory"

[dependencies.network_interface_card]
path = "../network_interface_card"

[dependencies.network_manager]
path = "../network_manager"

[dependencies.nic_buffers]
path = "../nic_buffers"

[lib]
crate-type = ["rlib"]
