[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "memory"
description = "The memory management subsystem"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9.4"
bitflags = "1.1.0"
xmas-elf = { version = "0.6.2", git = "https://github.com/theseus-os/xmas-elf.git" }
bit_field = "0.7.0"
zerocopy = "0.5.0"
log = "0.4.8"
lazy_static = { features = ["spin_no_std"], version = "1.4.0" }

atomic_linked_list = { path = "../../libs/atomic_linked_list" }
boot_info = { path = "../boot_info" }
kernel_config = { path = "../kernel_config" }
memory_structs = { path = "../memory_structs" }
page_table_entry = { path = "../page_table_entry" }
pte_flags = { path = "../pte_flags" }
page_allocator = { path = "../page_allocator" }
frame_allocator = { path = "../frame_allocator" }
no_drop = { path = "../no_drop" }
owned_borrowed_trait = { path = "../../libs/owned_borrowed_trait" }
frame_range_callbacks = { path = "../frame_range_callbacks" }

irq_safety = { git = "https://github.com/theseus-os/irq_safety" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14.8"
memory_x86_64 = { path = "../memory_x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
memory_aarch64 = { path = "../memory_aarch64" }

[lib]
crate-type = ["rlib"]
