[package]
name = "loadc"
version = "0.1.0"
description = "A convenience application for loading C language ELF executables."
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]
getopts = "0.2.21"
log = "0.4.8"
xmas-elf = { version = "0.6.2", git = "https://github.com/theseus-os/xmas-elf.git" }
rustc-demangle = "0.1.19"
libc = { version = "0.2.107", default-features = false }

[dependencies.app_io]
path = "../../kernel/app_io"

[dependencies.path]
path = "../../kernel/path"

[dependencies.fs_node]
path = "../../kernel/fs_node"

[dependencies.memory]
path = "../../kernel/memory"

[dependencies.mod_mgmt]
path = "../../kernel/mod_mgmt"

[dependencies.task]
path = "../../kernel/task"
