[package]
name = "pte_flags"
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>", "Kevin Boos <kevinaboos@gmail.com"]
description = "The bit flags for page table entries on x86_64 and aarch64."
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
bitflags = "1.3.2"
