[package]
name = "mm_eval"
version = "0.1.0"
description = "A application that microbenchmarks various memory mapping implementations"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]
getopts = "0.2.21"
cfg-if = "0.1.6"
libm = "0.2.1"

[dependencies.log]
version = "0.4.8"

[dependencies.hpet]
path = "../../kernel/acpi/hpet"

[dependencies.tsc]
path = "../../kernel/tsc"

[dependencies.kernel_config]
path = "../../kernel/kernel_config"

[dependencies.memory]
path = "../../kernel/memory"

[dependencies.memory_structs]
path = "../../kernel/memory_structs"

[dependencies.terminal_print]
path = "../../kernel/terminal_print"

[dependencies.apic]
path = "../../kernel/apic"

[dependencies.runqueue]
path = "../../kernel/runqueue"

[dependencies.libtest]
path = "../../kernel/libtest"

[dependencies.mapper_spillful]
path = "../../kernel/mapper_spillful"
