[package]
name = "test_restartable"
version = "0.1.0"
authors = ["Namitha Liyanage <namithaliyanage@gmail.com>"]

[dependencies]
getopts = "0.2.21"
spin = "0.9.4"

[dependencies.log]
default-features = false
version = "0.4.8"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.app_io]
path = "../../kernel/app_io"
