[package]
name = "root"
version = "0.1.0"
authors = ["Andrew Pham <apham727@gmail.com>"]
description = "a special concrete implementation of the Directory trait; differs from VFSDirectory only in that there is no parent field, and any attempt to access a parent field will return some error value"

[dependencies]
spin = "0.4.5"
[target.'cfg(any(target_arch = "x86_64", target_arch="x86"))'.dependencies]
x86_64 = { path = "../../libs/x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = { path = "../../libs/aarch64" }
 # currently using our local copy, forked from Phil Opp's crate

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0"

[dependencies.fs_node]
path = "../fs_node"

[dependencies.log]
default-features = false
version = "0.3.7"


[lib]
crate-type = ["rlib"]