[package]
name = "rq_eval"
version = "0.1.0"
description = "A application that microbenchmarks runqueue performance"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]
getopts = "0.2.21"


[dependencies.log]
version = "0.4.8"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.hpet]
path = "../../kernel/acpi/hpet"

[dependencies.task]
path = "../../kernel/task"

[dependencies.cpu]
path = "../../kernel/cpu"

[dependencies.runqueue]
path = "../../kernel/runqueue"

[dependencies.app_io]
path = "../../kernel/app_io"

[dependencies.libtest]
path = "../../kernel/libtest"
