[package]
name = "rq_eval"
version = "0.1.0"
description = "A application that microbenchmarks runqueue performance"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]
getopts = "0.2.21"


[dependencies.log]
version = "0.4.8"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.hpet]
path = "../../kernel/acpi/hpet"

[dependencies.task]
path = "../../kernel/task"

[dependencies.apic]
path = "../../kernel/apic"

[dependencies.runqueue]
path = "../../kernel/runqueue"

[dependencies.terminal_print]
path = "../../kernel/terminal_print"

[dependencies.libtest]
path = "../../kernel/libtest"
