[package]
name = "color"
version = "0.1.0"
authors = ["Wenqiu Yu <yuwenqiuj@gmail.com>", "Kevin Boos <kevinaboos@gmail.com>"]
description = "A simple representation of the standard RGB color model"

[lib]
crate-type = ["rlib"]
