[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "single_simd_task_optimization"
description = "Support for a special optimization that allows a SIMD task to avoid saving SIMD registers when context switching, if it is the only SIMD task on its core"
version = "0.1.0"

[dependencies]
cfg-if = "0.1.6"

[dependencies.log]
version = "0.4.8"

[dependencies.task]
path = "../task"


[lib]
crate-type = ["rlib"]
