[package]
name = "example"
version = "0.1.0"
description = "An example application that shows how to write a basic application for Theseus."
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

[dependencies]
getopts = "0.2.21"

[dependencies.terminal_print]
path = "../../kernel/terminal_print"
