[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "ioapic"
description = "IOAPIC (I/O Advanced Programmable Interrupt Controller) support (x86 only) for Theseus"
version = "0.1.0"

[dependencies]
log = "0.4.8"
spin = "0.9.0"
volatile = "0.2.7"
owning_ref = { git = "https://github.com/theseus-os/owning-ref-rs" }
zerocopy = "0.5.0"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[dependencies.memory]
path = "../memory"



[lib]
crate-type = ["rlib"]
