[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "ioapic"
description = "IOAPIC (I/O Advanced Programmable Interrupt Controller) support (x86 only) for Theseus"
version = "0.1.0"
build = "../../build.rs"
edition = "2018"

[dependencies]
spin = "0.4.10"
volatile = "0.2.7"
owning_ref = { git = "https://github.com/kevinaboos/owning-ref-rs" }
zerocopy = "0.3.0"

[dependencies.lazy_static]
features = ["spin_no_std", "nightly"]
version = "1.2.0"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../memory"



[lib]
crate-type = ["rlib"]
