[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "event_types"
description = "Types of input and output events that flow throughout the system"
version = "0.1.0"

[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"

[dependencies.shapes]
path = "../shapes"

[dependencies.mouse_data]
path = "../../libs/mouse_data"

[lib]
crate-type = ["rlib"]
