[package]
name = "frame_buffer_text"
version = "0.1.0"
authors = ["Wenqiu Yu <qiuj@mail.bnu.edu.cn>"]


[dependencies]
spin = "0.4.5"
volatile = "0.1.0"

[dependencies.frame_buffer]
path = "../frame_buffer"

[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.serial_port]
path = "../serial_port"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "0.2.1"


