[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "driver_init"
description = "Code for handling the sequence required to initializing each driver"
version = "0.1.0"

[dependencies]


[dependencies.log]
default-features = false
version = "0.3.7"

[dependencies.dfqueue]
path = "../../libs/dfqueue"

[dependencies.input_event_types]
path = "../input_event_types"

[dependencies.ata_pio]
path = "../ata_pio"

[dependencies.memory]
path = "../memory"

[dependencies.apic]
path = "../apic"

[dependencies.e1000]
path = "../e1000"

[dependencies.acpi]
path = "../acpi"

[dependencies.pci]
path = "../pci"

[dependencies.keyboard]
path = "../keyboard"

[dependencies.mouse]
path = "../mouse"

[dependencies.usb_uhci]
path = "../usb_uhci"

[dependencies.usb_ehci]
path = "../usb_ehci"

[dependencies.usb_driver]
path = "../usb_driver"

[lib]
crate-type = ["rlib"]
