[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "state_transfer"
description = "state transfer functions for applying during evolutionary crate swapping"
version = "0.1.0"

[dependencies]
spin = "0.9.0"


[dependencies.log]
version = "0.4.8"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.4.0"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.task]
path = "../task"

[dependencies.memory]
path = "../memory"

[dependencies.mod_mgmt]
path = "../mod_mgmt"

[dependencies.runqueue_round_robin]
path = "../runqueue_round_robin"

[dependencies.runqueue_priority]
path = "../runqueue_priority"

[dependencies.hpet]
path = "../acpi/hpet"

[lib]
crate-type = ["rlib"]
