[package]
name = "acpi_table_handler"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Functions for handling specific types of ACPI tables"
edition = "2021"

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../../memory"

[dependencies.acpi_table]
path = "../acpi_table"

[dependencies.rsdt]
path = "../rsdt"

[dependencies.fadt]
path = "../fadt"

[dependencies.hpet]
path = "../hpet"

[dependencies.madt]
path = "../madt"

[dependencies.dmar]
path = "../dmar"
