[package]
name = "sdt"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI SDT and other descriptor tables"

[dependencies]
zerocopy = "0.5.0"
static_assertions = "1.1.0"

