[package]
name = "memfs"
version = "0.1.0"
authors = ["Andrew Pham <apham727@gmail.com>, Christine Wang <chrissywang54@gmail.com"]
description = "contains the MappedPages-backed implementation of the fs_node traits"


[dependencies]
spin = "0.9.0"

[dependencies.fs_node]
path = "../fs_node"

[dependencies.memory]
path = "../memory"

[dependencies.log]
version = "0.4.8"

[dependencies.io]
path = "../io"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[lib]
crate-type = ["rlib"]
