[package]
name = "rsdt"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI RSDT and XSDT"


[dependencies.memory]
path = "../../memory"

[dependencies.sdt]
path = "../sdt"

[dependencies.acpi_table]
path = "../acpi_table"

