[package]
name = "upd"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Front-end application to communicate with Theseus update server"

[dependencies]
getopts = "0.2.21"
spin = "0.9.4"

[dependencies.itertools]
version = "0.7.9"
default-features = false

[dependencies.app_io]
path = "../../kernel/app_io"

[dependencies.mod_mgmt]
path = "../../kernel/mod_mgmt"

[dependencies.crate_swap]
path = "../../kernel/crate_swap"

[dependencies.memory]
path = "../../kernel/memory"

[dependencies.task]
path = "../../kernel/task"

[dependencies.path]
path = "../../kernel/path"

[dependencies.memfs]
path = "../../kernel/memfs"

[dependencies.fs_node]
path = "../../kernel/fs_node"

[dependencies.vfs_node]
path = "../../kernel/vfs_node"

[dependencies.ota_update_client]
path = "../../kernel/ota_update_client/"

[dependencies.net]
path = "../../kernel/net"
