[package]
name = "madt"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for ACPI MADT"
edition = "2021"

[dependencies]
zerocopy = "0.5.0"
log = "0.4.8"

[dependencies.memory]
path = "../../memory"

[dependencies.pic]
path = "../../pic"

[dependencies.apic]
path = "../../apic"

[dependencies.ioapic]
path = "../../ioapic"

[dependencies.sdt]
path = "../sdt"

[dependencies.acpi_table]
path = "../acpi_table"
