[package]
name = "window"
version = "0.1.0"
authors = ["Yue Wu <wuyue16@pku.edu.cn>", "Wenqiu Yu <yuwenqiuj@gmail.com>"]
description = "an easy-to-use window object owned by application"

[dependencies]
spin = "0.9.0"
owning_ref = { git = "https://github.com/theseus-os/owning-ref-rs" }
mpmc = "0.1.6"

[dependencies.log]
version = "0.4.8"

[dependencies.shapes]
path = "../shapes"

[dependencies.color]
path = "../color"

[dependencies.framebuffer_drawer]
path = "../framebuffer_drawer"

[dependencies.window_inner]
path = "../window_inner"

[dependencies.window_manager]
path = "../window_manager"

[dependencies.framebuffer]
path = "../framebuffer"

[dependencies.event_types]
path = "../event_types"

[dependencies.spawn]
path = "../spawn"

[dependencies.mouse]
path = "../mouse"

[dependencies.path]
path = "../../kernel/path"

[lib]
crate-type = ["rlib"]
