[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>", "Ramla Ijaz <ijazramla@gmail.com"]
name = "block_allocator"
version = "0.1.0"

[dependencies.linked_list_allocator]
version = "0.9.1"
default-features = false
features = [ "const_mut_refs" ]
