[package]
name = "keyboard_echo"
version = "0.1.0"
authors = ["Zhiyao Ma <zm16@pku.edu.cn>"]
build = "../../build.rs"

[dependencies]
core2 = { version = "0.3.2", default-features = false, features = ["alloc", "nightly"] }

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.app_io]
path = "../app_io"

[dependencies.log]
version = "0.4.8"

[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"

[lib]
crate-type = ["rlib"]
