[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "per_cpu"
description = "Support for defining per-CPU data types"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.8"
memoffset = "0.8.0"

cpu = { path = "../cpu" }
cpu_local = { path = "../cpu_local" }
no_drop = { path = "../no_drop" }
task = { path = "../task" }
