[package]
name = "terminal_print"
version = "0.1.0"
authors = ["Andrew Pham <apham727@gmail.com>"]
description = "Offers applications the ability to print to the terminal via the print! and println! macros"
build = "../../build.rs"


[dependencies]
spin = "0.4.5"
x86_64 = { path = "../../libs/x86_64" }

[dependencies.dfqueue]
path = "../../libs/dfqueue"

[dependencies.task]
path = "../../kernel/task"

[dependencies.serial_port]
path = "../../kernel/serial_port"


[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0"

[dependencies.event_types]
path = "../../kernel/event_types"
