[package]
name = "diff_crates"
version = "0.1.0"
description = "A tool for differencing crates' object files across builds of Theseus to see what has changed"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]


[dependencies]
getopts = "0.2"
walkdir = "2.2.7"
qp-trie = "0.8.0"
multimap = "0.4.0"
spin = "0.5.0"
serde_json = "1.0.39"