[package]
authors = ["Jacob Earle <earlejacobt@gmail.com>"]
name = "runqueue_realtime"
description = "Functions and types for handling runqueues in a realtime scheduling context"
version = "0.1.0"

[dependencies.task]
path = "../task"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.log]
version = "0.4.8"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.2.0"

[dependencies.atomic_linked_list]
path = "../../libs/atomic_linked_list"

[lib]
crate-type = ["rlib"]
