[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "stack"
description = "Defines the Stack type (a task's stack memory) and functions to allocate them"
version = "0.1.0"

[dependencies]
spin = "0.9.0"

[dependencies.log]
version = "0.4.8"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.memory_structs]
path = "../memory_structs"

[dependencies.page_allocator]
path = "../page_allocator"

[dependencies.memory]
path = "../memory"

[lib]
crate-type = ["rlib"]
