[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "storage_manager"
description = "A crate for managing storage devices/drives"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
spin = "0.4.10"
owning_ref = { git = "https://github.com/kevinaboos/owning-ref-rs" }


[dependencies.log]
version = "0.4.8"

[dependencies.lazy_static]
features = ["spin_no_std", "nightly"]
version = "1.2.0"

[dependencies.storage_device]
path = "../storage_device"

[dependencies.pci]
path = "../pci"

[dependencies.ata]
path = "../ata"

[lib]
crate-type = ["rlib"]
