[package]
authors = ["Ramla Ijaz <ijazramla@gmail.com>"]
name = "simple_ipc"
description = "An extremely basic mechanism for IPC that uses a lock-free shared buffer"
version = "0.1.0"

[dependencies]
bit_field = "0.7.0"

[dependencies.log]
version = "0.4.8"


[lib]
crate-type = ["rlib"]
