[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "memory_x86_64"
description = "The memory subsystem interfaces on x86_64."
version = "0.1.0"

[dependencies]
x86_64 = "0.14.8"

[dependencies.log]
version = "0.4.8"

[dependencies.boot_info]
path = "../boot_info"

[dependencies.kernel_config]
path = "../kernel_config"

[dependencies.pte_flags]
path = "../pte_flags"

[dependencies.memory_structs]
path = "../memory_structs"

[lib]
crate-type = ["rlib"]
