[package]
name = "porthole"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpmc = "0.1.6"
spin = "0.9.0"
zerocopy = "0.5.0"
core2 = { version = "0.4.0", default-features = false, features = ["alloc", "nightly"] }

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../../kernel/memory"

[dependencies.memory_structs]
path = "../../kernel/memory_structs"

[target.'cfg(target_arch = "x86_64")'.dependencies]
page_attribute_table = { path = "../../kernel/page_attribute_table" }

[dependencies.multicore_bringup]
path = "../../kernel/multicore_bringup"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.task]
path = "../../kernel/task"

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.stdio]
path = "../../libs/stdio"

[dependencies.hpet]
path = "../../kernel/acpi/hpet"

[dependencies.mouse_data]
path = "../../libs/mouse_data"

[dependencies.mouse]
path = "../../kernel/mouse"

[dependencies.event_types]
path = "../../kernel/event_types"

[dependencies.keycodes_ascii]
path = "../../libs/keycodes_ascii"

[dependencies.font]
path = "../../kernel/font"

[dependencies.device_manager]
path = "../../kernel/device_manager"

[lib]
crate-type = ["rlib"]