[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "context_switch_sse"
description = "Context switching routines and structs for SSE-enabled register sets"
version = "0.1.0"

[dependencies]
zerocopy = "0.5.0"

[dependencies.context_switch_regular]
path = "../context_switch_regular"

[lib]
crate-type = ["rlib"]
