[package]
name = "acpi_table"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Definitions for ACPI tables bookkeeping"

[dependencies]
zerocopy = "0.5.0"

[dependencies.log]
version = "0.4.8"

[dependencies.memory]
path = "../../memory"

[dependencies.sdt]
path = "../sdt"
