[package]
name = "hpet"
version = "0.1.0"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
description = "Support for the x86 HPET: High Precision Event Timer"
edition = "2021"

[dependencies]
spin = "0.9.4"
volatile = "0.2.7"
zerocopy = "0.5.0"

[dependencies.log]
version = "0.4.8"

[dependencies.kernel_config]
path = "../../kernel_config"

[dependencies.memory]
path = "../../memory"

[dependencies.sdt]
path = "../sdt"

[dependencies.acpi_table]
path = "../acpi_table"

[dependencies.time]
path = "../../time"
