[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "test_lib"
version = "0.1.0"

[dependencies]
# rlibc = "1.0.0"
# spin = "0.4.5"

#3[dependencies.kernel_config]
#3path = "../kernel_config"

# [dependencies.log]
# default-features = false
# version = "0.3.7"

# [dependencies.nano_core]
# path = "../nano_core"

# [dependencies.vga_buffer]
# path = "../vga_buffer"

[build]
rustflags = ["-C", "prefer-dynamic", "-C", "link-args=-fPIC"]
# , "-C", "panic=abort"
# "-C", "code-model=large"

[lib]
crate-type = ["rlib"] # "lib" does the same thing I think
