[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "logger"
version = "0.1.0"

[dependencies]
spin = "0.9.0"
log = "0.4.8"

[dependencies.irq_safety]
git = "https://github.com/theseus-os/irq_safety"

[dependencies.serial_port_basic]
path = "../serial_port_basic"

[lib]
crate-type = ["rlib"]
