[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "logger"
version = "0.1.0"
build = "../../build.rs"

[dependencies]
spin = "0.4.10"

[dependencies.serial_port]
path = "../serial_port"

[dependencies.log]
version = "0.4.8"


[lib]
crate-type = ["rlib"]
