[package]
name = "displayable"
version = "0.1.0"
authors = ["Wenqiu Yu <yuwenqiuj@gmail.com>"]
description = "provides a Displayable trait, which abstracts objects that can display themselves onto a framebuffer"

[dependencies]
spin = "0.9.0"

[dependencies.framebuffer]
path = "../framebuffer"

[dependencies.color]
path = "../color"

[dependencies.shapes]
path = "../shapes"

[lib]
crate-type = ["rlib"]
