[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "tsc"
description = "TSC (TimeStamp Counter) support for performance counters on x86. Basically a wrapper around rdtsc."
version = "0.1.0"

[dependencies]

[dependencies.log]
version = "0.4.8"

[dependencies.pit_clock]
path = "../pit_clock"


[lib]
crate-type = ["rlib"]
