[package]
name = "heap_eval"
version = "0.1.0"
description = "Benchmarks to evaluate Theseus's heap design"
authors = ["Ramla Ijaz <ijazramla@gmail.com>"]

[dependencies]
qp-trie = "0.8.0"
getopts = "0.2.21"

[dependencies.terminal_print]
path = "../../kernel/terminal_print"

[dependencies.log]
version = "0.4.8"

[dependencies.hpet]
path = "../../kernel/acpi/hpet"

[dependencies.apic]
path = "../../kernel/apic"

[dependencies.runqueue]
path = "../../kernel/runqueue"

[dependencies.hashbrown]
version = "0.11.2"
features = ["nightly"]

[dependencies.libtest]
path = "../../kernel/libtest"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.heap]
path = "../../kernel/heap"

